### ISSUE TITLE
Baffling spec error during coercion

### ISSUE THREAD

**Issue by j0ni** [metosin/reitit#282]
I'm encountering the following exception and have no real idea how to begin debugging. You can find some [extra data captured in the exception here](https://gist.github.com/j0ni/5ee3674e72daf925eca768c76c7d6569).

```
java.lang.IllegalArgumentException: No implementation of method: :specize* of protocol: #'clojure.spec.alpha/Specize found for class: nil
	at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:583)
	at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:575)
	at clojure.spec.alpha$fn__1782$G__1777__1791.invoke(alpha.clj:121)
	at clojure.spec.alpha$specize.invokeStatic(alpha.clj:152)
	at clojure.spec.alpha$specize.invoke(alpha.clj:151)
	at clojure.spec.alpha$form.invokeStatic(alpha.clj:177)
	at clojure.spec.alpha$form.invoke(alpha.clj:173)
	at spec_tools.parse$parse_spec.invokeStatic(parse.cljc:31)
	at spec_tools.parse$parse_spec.invoke(parse.cljc:18)
	at spec_tools.parse$parse_spec_with_spec_ref.invokeStatic(parse.cljc:53)
	at spec_tools.parse$parse_spec_with_spec_ref.invoke(parse.cljc:52)
	at spec_tools.parse$fn__35053.invokeStatic(parse.cljc:177)
	at spec_tools.parse$fn__35053.invoke(parse.cljc:175)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at spec_tools.parse$parse_spec.invokeStatic(parse.cljc:39)
	at spec_tools.parse$parse_spec.invoke(parse.cljc:18)
	at spec_tools.core$create_spec.invokeStatic(core.cljc:520)
	at spec_tools.core$create_spec.invoke(core.cljc:490)
	at spec_tools.core.Spec$specify__35317.invoke(core.cljc:382)
	at spec_tools.core.Spec$fn__35319.invoke(core.cljc:389)
	at spec_tools.core$fn__35281$fn__35283.invoke(core.cljc:321)
	at clojure.core$fn__8429$fn__8431.invoke(core.clj:6840)
	at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
	at clojure.core.protocols$fn__8140.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8140.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8088$G__8083__8101.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6828)
	at clojure.core$fn__8429.invokeStatic(core.clj:6830)
	at clojure.core$fn__8429.invoke(core.clj:6830)
	at clojure.core.protocols$fn__8167$G__8162__8176.invoke(protocols.clj:175)
	at clojure.core$reduce_kv.invokeStatic(core.clj:6856)
	at clojure.core$reduce_kv.invoke(core.clj:6847)
	at spec_tools.core$fn__35281.invokeStatic(core.cljc:318)
	at spec_tools.core$fn__35281.invoke(core.cljc:316)
	at clojure.lang.MultiFn.invoke(MultiFn.java:244)
	at spec_tools.core.Spec._coerce(core.cljc:389)
	at spec_tools.core$coerce.invokeStatic(core.cljc:230)
	at spec_tools.core$coerce.invoke(core.cljc:224)
	at spec_tools.core$coerce.invokeStatic(core.cljc:228)
	at spec_tools.core$coerce.invoke(core.cljc:224)
	at reitit.coercion.spec$create$reify__36041$fn__36089.invoke(spec.cljc:122)
	at reitit.coercion$request_coercer$fn__33739.invoke(coercion.cljc:84)
	at reitit.coercion$coerce_request$fn__33750.invoke(coercion.cljc:113)
	at clojure.core$fn__8429$fn__8431.invoke(core.clj:6840)
	at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
	at clojure.core.protocols$fn__8140.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8140.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8088$G__8083__8101.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6828)
	at clojure.core$fn__8429.invokeStatic(core.clj:6830)
	at clojure.core$fn__8429.invoke(core.clj:6830)
	at clojure.core.protocols$fn__8167$G__8162__8176.invoke(protocols.clj:175)
	at clojure.core$reduce_kv.invokeStatic(core.clj:6856)
	at clojure.core$reduce_kv.invoke(core.clj:6847)
	at reitit.coercion$coerce_request.invokeStatic(coercion.cljc:111)
	at reitit.coercion$coerce_request.invoke(coercion.cljc:110)
	at reitit.ring.coercion$fn__36483$fn__36485$fn__36486.invoke(coercion.cljc:39)
	at reitit.ring.coercion$fn__36492$fn__36494$fn__36495.invoke(coercion.cljc:63)
	at muuntaja.middleware$wrap_format_request$fn__36305.invoke(middleware.clj:114)
	at reitit.ring.middleware.exception$wrap$fn__36120$fn__36121.invoke(exception.clj:49)
	at muuntaja.middleware$wrap_format_response$fn__36309.invoke(middleware.clj:132)
	at muuntaja.middleware$wrap_format_negotiate$fn__36302.invoke(middleware.clj:96)
	at ring.middleware.params$wrap_params$fn__36268.invoke(params.clj:67)
	at reitit.ring$ring_handler$fn__33540.invoke(ring.cljc:286)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at backend_big_enos.handler_test$fn__34316$fn__34622$fn__34659.invoke(handler_test.clj:431)
	at clojure.core$with_redefs_fn.invokeStatic(core.clj:7514)
	at clojure.core$with_redefs_fn.invoke(core.clj:7498)
	at backend_big_enos.handler_test$fn__34316$fn__34622.invoke(handler_test.clj:410)
	at backend_big_enos.handler_test$fn__34316.invokeStatic(handler_test.clj:320)
	at backend_big_enos.handler_test$fn__34316.invoke(handler_test.clj:168)
	at circleci.test$test_STAR_.invokeStatic(test.clj:75)
	at circleci.test$test_STAR_.invoke(test.clj:71)
	at circleci.test$test_var_STAR_$fn__1523$fn__1524$fn__1525.invoke(test.clj:92)
	at backend_big_enos.handler_test$eval36379$fn__36380.invoke(form-init1231751341270438460.clj:1452)
	at clojure.test$compose_fixtures$fn__9731$fn__9732.invoke(test.clj:694)
	at backend_big_enos.test_utils$full_stack_fixture$fn__21447.invoke(form-init1231751341270438460.clj:406)
	at backend_common.test_utils$with_test_queues$fn__21303.invoke(test_utils.clj:23)
	at clojure.core$with_redefs_fn.invokeStatic(core.clj:7514)
	at clojure.core$with_redefs_fn.invoke(core.clj:7498)
	at backend_common.test_utils$with_test_queues.invokeStatic(test_utils.clj:18)
	at backend_common.test_utils$with_test_queues.invoke(test_utils.clj:14)
	at backend_common.test_utils$with_test_queues.invokeStatic(test_utils.clj:28)
	at backend_common.test_utils$with_test_queues.invoke(test_utils.clj:14)
	at backend_big_enos.test_utils$full_stack_fixture.invokeStatic(form-init1231751341270438460.clj:348)
	at backend_big_enos.test_utils$full_stack_fixture.invoke(form-init1231751341270438460.clj:346)
	at clojure.test$compose_fixtures$fn__9731$fn__9732.invoke(test.clj:694)
	at clojure.test$default_fixture.invokeStatic(test.clj:687)
	at clojure.test$default_fixture.invoke(test.clj:683)
	at clojure.test$compose_fixtures$fn__9731.invoke(test.clj:694)
	at clojure.test$compose_fixtures$fn__9731.invoke(test.clj:694)
	at circleci.test$test_var_STAR_$fn__1523$fn__1524.invoke(test.clj:92)
	at clojure.test$default_fixture.invokeStatic(test.clj:687)
	at clojure.test$default_fixture.invoke(test.clj:683)
	at circleci.test$once_fixtures$fn__1491.invoke(test.clj:49)
	at circleci.test$test_var_STAR_$fn__1523.invoke(test.clj:90)
	at circleci.test$make_global_fixture$fn__1500.invoke(test.clj:56)
	at circleci.test$test_var_STAR_.invokeStatic(test.clj:88)
	at circleci.test$test_var_STAR_.invoke(test.clj:77)
	at circleci.test$test_var.invokeStatic(test.clj:120)
	at circleci.test$test_var.invoke(test.clj:104)
	at circleci.test$test_var.invokeStatic(test.clj:110)
	at circleci.test$test_var.invoke(test.clj:104)
	at backend_big_enos.handler_test$eval38190.invokeStatic(form-init1231751341270438460.clj:13)
	at backend_big_enos.handler_test$eval38190.invoke(form-init1231751341270438460.clj:13)
	at clojure.lang.Compiler.eval(Compiler.java:7177)
	at clojure.lang.Compiler.eval(Compiler.java:7132)
	at clojure.core$eval.invokeStatic(core.clj:3214)
	at clojure.core$eval.invoke(core.clj:3210)
	at clojure.main$repl$read_eval_print__9086$fn__9089.invoke(main.clj:437)
	at clojure.main$repl$read_eval_print__9086.invoke(main.clj:437)
	at clojure.main$repl$fn__9095.invoke(main.clj:458)
	at clojure.main$repl.invokeStatic(main.clj:458)
	at clojure.main$repl.doInvoke(main.clj:368)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.core$apply.invoke(core.clj:660)
	at refactor_nrepl.ns.slam.hound.regrow$wrap_clojure_repl$fn__17334.doInvoke(regrow.clj:18)
	at clojure.lang.RestFn.invoke(RestFn.java:1523)
	at nrepl.middleware.interruptible_eval$evaluate.invokeStatic(interruptible_eval.clj:79)
	at nrepl.middleware.interruptible_eval$evaluate.invoke(interruptible_eval.clj:55)
	at nrepl.middleware.interruptible_eval$interruptible_eval$fn__4826$fn__4830.invoke(interruptible_eval.clj:142)
	at clojure.lang.AFn.run(AFn.java:22)
	at nrepl.middleware.session$session_exec$main_loop__4927$fn__4931.invoke(session.clj:171)
	at nrepl.middleware.session$session_exec$main_loop__4927.invoke(session.clj:170)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by j0ni** [comment]
FYI, this turned out to have been caused by a spec which was a `coll-of` something which was no longer defined. This is still a somewhat baffling error, so I'll leave it open in case @ikitommi you want to make a better message. Feel free to close though.

**Comment by ikitommi** [comment]
the `:reponses` should also be under `:body`, e.g. `{200 {:body ....}}`. The errors should be more detailed thou.

**Comment by miikka** [comment]
This issue seems to be about a clojure.spec error message, so I'm closing this now.
