### ISSUE TITLE
Syntax errors in http-swagger example

### ISSUE THREAD

**Issue by balljointedmae** [metosin/reitit#338]
Hi! The http-swagger example contains multiple syntax errors (missing end parens on the end of the math route being one of them). This resulted in lots of errors being produced, ending finally with this one
```
Exception in thread "main" clojure.lang.ArityException: Wrong number of args (4) passed to: manifold.executor/thread-factory
	at clojure.lang.AFn.throwArity(AFn.java:429)
	at clojure.lang.AFn.invoke(AFn.java:44)
	at aleph.netty$enumerating_thread_factory.invokeStatic(netty.clj:746)
	at aleph.netty$enumerating_thread_factory.invoke(netty.clj:744)
	at aleph.netty$start_server.invokeStatic(netty.clj:945)
	at aleph.netty$start_server.invoke(netty.clj:936)
	at aleph.http.server$start_server.invokeStatic(server.clj:480)
	at aleph.http.server$start_server.invoke(server.clj:445)
	at aleph.http$start_server.invokeStatic(http.clj:53)
	at aleph.http$start_server.invoke(http.clj:28)
	at redblackrose.core$start.invokeStatic(core.clj:138)
	at redblackrose.core$start.invoke(core.clj:137)
	at redblackrose.core$_main.invokeStatic(core.clj:142)
	at redblackrose.core$_main.invoke(core.clj:141)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at redblackrose.core.main(Unknown Source)
```

**Comment by miikka** [comment]
I tried run `lein repl` in examples/http-swagger and it works just fine. Are you sure you haven't again copy-pasted the code badly?

**Comment by gigavinyl** [comment]
Yes, I downloaded them via wget. I'm running the uberjar if that matters.

**Comment by miikka** [comment]
Can you share the code you're running?

**Comment by gigavinyl** [comment]
``` clojure
(ns redblackrose.core
  (:require [reitit.ring :as ring]
            [reitit.http :as http]
            [reitit.coercion.spec]
            [reitit.swagger :as swagger]
            [reitit.swagger-ui :as swagger-ui]
            [reitit.http.coercion :as coercion]
            [reitit.dev.pretty :as pretty]
            [reitit.interceptor.sieppari :as sieppari]
            [reitit.http.interceptors.parameters :as parameters]
            [reitit.http.interceptors.muuntaja :as muuntaja]
            [reitit.http.interceptors.exception :as exception]
            ;; [reitit.http.interceptors.multipart :as multipart]
            [reitit.http.interceptors.dev :as dev]
            [reitit.http.spec :as spec]
            [spec-tools.spell :as spell]
            [aleph.http :as aleph]
            [muuntaja.core :as m]
            [clojure.java.io :as io]
            [clojure.spec.alpha :as s]
            [spec-tools.core :as st]
            [manifold.deferred :as d])
  (:gen-class))

(s/def ::x int?)
(s/def ::y int?)
(s/def ::total pos-int?)

(s/def ::seed string?)
(s/def ::results
  (st/spec
    {:spec (s/and int? #(< 0 % 100))
     :description "between 1-100"
     :swagger/default 10
     :reason "invalid number"}))

(def app
  (http/ring-handler
   (http/router
    [["/swagger.json"
      {:get {:no-doc true
             :swagger {:info {:title "my-api"
                              :description "with reitit-http"}}
             :handler (swagger/create-swagger-handler)}}]

     ["/files"
      {:swagger {:tags ["files"]}}


      ;; ["/download"
      ;;  {:get {:summary "downloads a file"
      ;;         :swagger {:produces ["image/png"]}
      ;;         :handler (fn [_]
      ;;                    {:status 200
      ;;                     :headers {"Content-Type" "image/png"}
      ;;                     :body (io/input-stream
      ;;                            (io/resource "reitit.png"))})}}]]

      ["/async"
       {:get {:swagger {:tags ["async"]}
              :summary "fetches random users asynchronously over the internet"
              :parameters {:query (s/keys :req-un [::results] :opt-un [::seed])}
              :responses {200 {:body any?}}
              :handler (fn [{{{:keys [seed results]} :query} :parameters}]
                         (d/chain
                          (aleph/get
                           "https://randomuser.me/api/"
                           {:query-params {:seed seed, :results results}})
                          :body
                          (partial m/decode "application/json")
                          :results
                          (fn [results]
                            {:status 200
                             :body results})))}}]

      ["/math"
       {:swagger {:tags ["math"]}}

       ["/plus"
        {:get {:summary "plus with data-spec query parameters"
               :parameters {:query {:x int?, :y int?}}
               :responses {200 {:body {:total pos-int?}}}
               :handler (fn [{{{:keys [x y]} :query} :parameters}]
                          {:status 200
                           :body {:total (+ x y)}})}
         :post {:summary "plus with data-spec body parameters"
                :parameters {:body {:x int?, :y int?}}
                :responses {200 {:body {:total int?}}}
                :handler (fn [{{{:keys [x y]} :body} :parameters}]
                           {:status 200
                            :body {:total (+ x y)}})}}]

       ["/minus"
        {:get {:summary "minus with clojure.spec query parameters"
               :parameters {:query (s/keys :req-un [::x ::y])}
               :responses {200 {:body (s/keys :req-un [::total])}}
               :handler (fn [{{{:keys [x y]} :query} :parameters}]
                          {:status 200
                           :body {:total (- x y)}})}
         :post {:summary "minus with clojure.spec body parameters"
                :parameters {:body (s/keys :req-un [::x ::y])}
                :responses {200 {:body (s/keys :req-un [::total])}}
                :handler (fn [{{{:keys [x y]} :body} :parameters}]
                           {:status 200
                            :body {:total (- x y)}})}}]]]

     {:reitit.interceptor/transform dev/print-context-diffs ;; pretty context diffs
      :validate spec/validate ;; enable spec validation for route data
      :reitit.spec/wrap spell/closed ;; strict top-level validation
      :exception pretty/exception
      :data {:coercion reitit.coercion.spec/coercion
             :muuntaja m/instance
             :interceptors [;; swagger feature
                            swagger/swagger-feature
                            ;; query-params & form-params
                            (parameters/parameters-interceptor)
                            ;; content-negotiation
                            (muuntaja/format-negotiate-interceptor)
                            ;; encoding response body
                            (muuntaja/format-response-interceptor)
                            ;; exception handling
                            (exception/exception-interceptor)
                            ;; decoding request body
                            (muuntaja/format-request-interceptor)
                            ;; coercing response bodys
                            (coercion/coerce-response-interceptor)
                            ;; coercing request parameters
                            (coercion/coerce-request-interceptor)]}}
     (ring/routes
      (swagger-ui/create-swagger-ui-handler
       {:path "/"
        :config {:validatorUrl nil
                 :operationsSorter "alpha"}})
      (ring/create-default-handler))
     {:executor sieppari/executor}])))

(defn start []
  (aleph/start-server (aleph/wrap-ring-async-handler #'app) {:port 3000})
  (println "server running in port 3000"))

(defn -main []
  (start))

(comment
  (start))
```

**Comment by miikka** [comment]
I don't know why you get the exception, but your call to `http/router` isn't quite right. The route vector should end with the `["/minus" ...]` route, but now it also contains the metadata map and the `(ring/routes ...)` call. Try taking them out and see if it works.

**Comment by miikka** [comment]
This is an old issue so I'm closing this. If you're still having this problem, please re-open this or open a new issue with more information.
